### ISSUE TITLE
Possible vertex alpha bug

### ISSUE THREAD

**Issue by dwhite4** [travnick/CryBlend#180]
I am not sure of the current state of vertex alpha.  I have not tested it recently and fear that it may not be working as expected.  If anyone wants to look into this, that would be incredibly useful.  Also, the old vertex alpha used white and red for the colors.  But I feel like black and white would make more sense.

**Comment by ochounos** [comment]
Heard that the colors are inverted, I mean, using black must be white and white must be black, need to check. I'm not sure if still red is being used or already black and white. Let me have a look about it, right now I have no idea what is there.

**Comment by ochounos** [comment]
Seems that vertex alpha is deprecated, I couldn't find the way to use it. Last doc is from 2014 and some parts there are already deprecated. You can achieve this now with blend mask. I was checking the code, vertex colours are properly exported and the alpha channel is calculated as average of sum of all colours, so it means grey, not red anymore.

Can some of you check if this can still be used on cryengine? Otherwise we should close this issue, seems deprecated already.

**Comment by ochounos** [comment]
@dwhite4 Can you find a way to test it or can we close this as deprecated functionality in latest cryengine? If people use old version maybe they can report any error there, anyway, it will be hard for us to check it if we are not keeping old versions.

**Comment by dwhite4** [comment]
@ochounos I'd like to keep support for the Free SDK.  I will find a way to test this when I get a chance.

**Comment by ochounos** [comment]
Ok, seems not deprecated, I'm trying to test it. Seems exporting well the alpha value per vertex but it's not working on cryengine. Trying to figure out what I'm doing wrong.

**Comment by ochounos** [comment]
Ok, tested, it's working, just forgot to rename vertex color group to "alpha". Works with black and white (and all the grey scale). Let me know if it's not working for you.

**Comment by dwhite4** [comment]
Sounds good, I'll test it today and get back to you.

**Comment by dwhite4** [comment]
Alright tested, everything looks alright.  I will close.
